docker/Dockerfile:  Made some very minor changes to reduce the size of the resulting image. auth/authentication.py:  Fixed a bug in regards to users with unicode usernames.  This should resolve issue #467 (https://github.com/liftoff/GateOne/issues/467). app_terminal.py:  Fixed a bug where you'd get an exception, "AttributeError: 'bytes' object has no attribute 'format'" in Python 3.  This should resolve issue #466 (https://github.com/liftoff/GateOne/issues/466). app_terminal.py:  Fixed a bug in `TerminalApplication.get_webworker()` where you'd get a TypeError exception like, "term_ww.js is not JSON serializable" in Python 3. core/server.py:  Fixed a bug where the call to `applications.sort()` inside `ApplicationWebSocket.list_applications()` would result in an exception in Python 3.